# Creating groups
POST http://localhost:3000/groups
Content-Type: application/json

{
  "name": "テストグループ1",
  "members": ["一郎", "二郎", "三郎"]
}

###

# Get group list
GET http://localhost:3000/groups

###

# Get a group by specifying the group name
GET http://localhost:3000/groups/テストグループ1

###

# Register expenses
POST http://localhost:3000/expenses
Content-Type: application/json

{
  "groupName": "テストグループ1",
	"expenseName": "ディナー",
	"payer": "一郎",
	"amount": 10000
}

###

# Get liquidation list
GET http://localhost:3000/settlements/テストグループ1

###

# Initialize test data
GET http://localhost:3000/init